name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build Executable
        run: |
          pyinstaller --onefile tm_sf_server.py

      - name: Prepare Build Directory
        shell: pwsh
        run: |
          # Create builds/win directory if it doesn't exist
          if (-Not (Test-Path -Path "builds/win")) {
              New-Item -ItemType Directory -Path "builds/win" | Out-Null
              Write-Host "Created directory builds/win"
          } else {
              Write-Host "Directory builds/win already exists"
          }
          
          # Remove existing executables in builds/win
          Remove-Item -Path "builds/win/*" -Recurse -Force -ErrorAction SilentlyContinue
          Write-Host "Cleared existing files in builds/win"

      - name: Move Executable
        shell: pwsh
        run: |
          Move-Item -Path "dist\tm_sf_server.exe" -Destination "builds/win\" -Force
          Write-Host "Moved tm_sf_server.exe to builds/win"

      - name: Commit Built Executable
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Add Windows build'
          branch: main
          file_pattern: 'builds/win/tm_sf_server.exe'
